### PR TITLE
object_store get_opts streams chunked bytes

### PR DESCRIPTION
**Pull request by milenkovicm**
get_opts streams bytes instead of loading whole file

### CODE REVIEW

**Comment by milenkovicm** [comment]
It's a draft PR, tests pass but I'd like to add a bit more. 
will update PR with more tests if PRs are accepted

**Comment by Kimahriman** [comment]
Thanks for the PR! I'm actually working on trying to implement `AsyncWrite` for the FileWriter for direct `put_multipart` support. I haven't thought about the reader side much but trying to implement `AsyncRead` on the reader side might be a good way to directly support this too (it's very difficult to implement those traits but I am sort of finally figuring it out)

**Comment by Kimahriman** [comment]
If you can merge in the latest master I turned on workflows for PRs

**Comment by Kimahriman** [comment]
Actually had a change of heart on this because each read call currently has to create a new connection to a data node. Instead I decided to update a lot of the internal reading setup to operate on streams, to expose a public method for returning a stream from a file: https://github.com/Kimahriman/hdfs-native/pull/34

**Comment by milenkovicm** [comment]
we can close this one, and re-open it later with updated code if needed

**Pull request closed without merging**
